before_script:
    - composer self-update
    - composer install --dev
language: php
php:
    - 5.4
    - 5.5
script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
    email: false
